// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA43lvBkl9W9zKSjEznl_F4RUF8boua3xk',
    appId: '1:243273096094:web:e39ee769153bda5242948f',
    messagingSenderId: '243273096094',
    projectId: 'voting-3fe5d',
    authDomain: 'voting-3fe5d.firebaseapp.com',
    storageBucket: 'voting-3fe5d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4cU2pE8YgEpUiDjb1sAEiw2mz2aF919A',
    appId: '1:243273096094:android:205699220c3bf6e142948f',
    messagingSenderId: '243273096094',
    projectId: 'voting-3fe5d',
    storageBucket: 'voting-3fe5d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDavjFJZFTNUAiU2MDOTywmMadlGZjncKY',
    appId: '1:243273096094:ios:e9f78f13511a0ddf42948f',
    messagingSenderId: '243273096094',
    projectId: 'voting-3fe5d',
    storageBucket: 'voting-3fe5d.appspot.com',
    iosBundleId: 'com.example.voting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDavjFJZFTNUAiU2MDOTywmMadlGZjncKY',
    appId: '1:243273096094:ios:e9f78f13511a0ddf42948f',
    messagingSenderId: '243273096094',
    projectId: 'voting-3fe5d',
    storageBucket: 'voting-3fe5d.appspot.com',
    iosBundleId: 'com.example.voting',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA43lvBkl9W9zKSjEznl_F4RUF8boua3xk',
    appId: '1:243273096094:web:79e76322539fddb142948f',
    messagingSenderId: '243273096094',
    projectId: 'voting-3fe5d',
    authDomain: 'voting-3fe5d.firebaseapp.com',
    storageBucket: 'voting-3fe5d.appspot.com',
  );
}
